@Alveus.Web_HostAddress = http://localhost:5081

GET {{Alveus.Web_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{Alveus.Web_HostAddress}}/agent/chat
Content-Type: application/json

{
  "message": "Allume la lumière du salon"
}

###
